name: Push commit to master

on:
  push:
    branches: [ master ]

jobs:
  Final_Release_Test:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Install dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test --no-restore --verbosity m

  Build_nupkg:
    needs: Final_Release_Test

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    container: mcr.microsoft.com/dotnet/core/sdk:3.1

    steps:
      - uses: actions/checkout@v2
      - name: Pack with dotnet
        run: dotnet pack Project/Project.csproj --output nuget-packages --configuration Release
      - name: Upload nupkg
        uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: nuget-packages/*.nupkg
          if-no-files-found: error

  Push_Nuget:
    name: Push nupkg to Nuget
    needs: Build_nupkg

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    container: mcr.microsoft.com/dotnet/core/sdk:3.1

    steps:
      - name: Download nupkg from build
        uses: actions/download-artifact@v2
        with:
          name: nupkg
          path: nuget-packages

      - name: Push to nuget
        run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_DEPLOY_KEY }} --source https://api.nuget.org/v3/index.json

  Push_GitHub:
    name: Push nupkg to GitHub
    needs: Build_nupkg

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    container: mcr.microsoft.com/dotnet/core/sdk:3.1

    steps:
      - name: Download nupkg from build
        uses: actions/download-artifact@v2
        with:
          name: nupkg
          path: nuget-packages
      - name: add github source
        run: dotnet nuget add source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json --name github --username ${{github.repository_owner}} --password ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text
      - name: Push to github
        run: dotnet nuget push nuget-packages/*.nupkg --source github
